
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-blog
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --host 0.0.0.0 --force_polling
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_UID=501
      - JEKYLL_GID=501
    working_dir: /srv/jekyll
